version: 2.1
orbs:
  node: circleci/node@4.1.0
  gcp-cli: circleci/gcp-cli@1.8.5
jobs:
  test:
    executor:
      name: node/default
    working_directory: ~/repo
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          override-ci-command: yarn install --ignore-engines
      - run: |
          yarn run test
          ls
  build:
    executor:
      name: node/default
    working_directory: ~/repo
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          override-ci-command: yarn install --ignore-engines
      - run: |
          yarn build
          pwd
          ls
      - save_cache:
          paths:
            - ~/repo/build
          key: v1-build-{{ .Branch }}-{{ checksum "~/repo/app.yaml" }}
workflows:
  test:
    jobs:
      - test:
          filters:
            branches:
              only:
                - develop
      - build:
          requires:
            - test
  nightly:
    triggers:
      - schedule:
          cron: "0 5 * * *"
          filters:
            branches:
              only:
                - develop
    jobs:
      - test