version: 2.1
orbs:
  node: circleci/node@4.1.0
  gcp-cli: circleci/gcp-cli@1.8.5
jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          override-ci-command: yarn install --ignore-engines
      - run:
          command: |
          yarn run test
          pwd
          name: Run YARN tests
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          override-ci-command: yarn install --ignore-engines
      - run:
          command: yarn run test
          name: Run YARN tests
workflows:
  test:
    jobs:
      - test
  nightly:
    triggers:
      - schedule:
          cron: "0 5 * * *"
          filters:
            branches:
              only:
                - develop
    jobs:
      - test